baseURL: "https://EnriqueCepeda.github.io"
languageCode: "en-us"
title: "Enrique Cepeda's blog"
theme: "PaperMod"
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: search
      weight: 10
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
params:
  homeInfoParams:
    Title: Hi there!
    Content: "This is the blog of a Software Developer based in Spain. I hope you like the content in case you want to check it out ;) (Or the future content, there is not content yet WIP LOL)"
  socialIcons:
    - name: "github"
    - url: "https://github.com/EnriqueCepeda"
    - name: "email"
    - url: "ecepedavillamayor@gmail.com"
    - name: "linkedin"
    - url: "https://www.linkedin.com/in/enrique-cepeda-villamayor-23154915a/"
outputs:
  home:
    - HTML
    - RSS
    - JSON
