baseURL: "https://EnriqueCepeda.github.io"
languageCode: "en-us"
title: "Enrique Cepeda"
theme: "PaperMod"
menu:
  main:
    - identifier: search
      name: search
      url: search
      weight: 10
params:
  defaultTheme: dark
  ShowFullTextinRSS: true
  homeInfoParams:
    Title: Hi there!
    Content: "These are just the thoughts of a Software Developer based in Ciudad Real (Spain), take them with a pinch of salt :)"
  socialIcons:
    - name: "github"
      url: "https://github.com/EnriqueCepeda"
    - name: "email"
      url: "mailto:ecepedavillamayor@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/enrique-cepeda-villamayor-23154915a/"
outputs:
  home:
    - HTML
    - RSS
    - JSON
